### ISSUE TITLE
editelementoption not work

### ISSUE THREAD

**Issue by xiphias-yu** [vfremaux/moodle-mod_tracker#25]
Hello,
Change the option is not working now.
Create a dropdown element, add some item, Save Changes.
Then Update options, Edit an element, then it's the bug.

![bug](https://user-images.githubusercontent.com/45279143/48935292-260bfd00-ef42-11e8-9c5d-54c188c1c5b1.png)

**Comment by soleimaniha** [comment]
Templates names must be specified as "componentname/templatename" (mod_tracker:editoroptions requested)

 Stack trace: 

    line 107 of /lib/classes/output/mustache_template_finder.php: coding_exception thrown
    line 54 of /lib/classes/output/mustache_filesystem_loader.php: call to core\output\mustache_template_finder::get_template_filepath()
    line 99 of /lib/mustache/src/Mustache/Loader/FilesystemLoader.php: call to core\output\mustache_filesystem_loader->getFileName()
    line 82 of /lib/mustache/src/Mustache/Loader/FilesystemLoader.php: call to Mustache_Loader_FilesystemLoader->loadFile()
    line 657 of /lib/mustache/src/Mustache/Engine.php: call to Mustache_Loader_FilesystemLoader->load()
    line 188 of /lib/outputrenderers.php: call to Mustache_Engine->loadTemplate()
    line 674 of /mod/tracker/renderer.php: call to renderer_base->render_from_template()
    line 204 of /mod/tracker/views/admin.controller.php: call to mod_tracker_renderer->edit_option_form()
    line 131 of /mod/tracker/view.php: call to include()

**Comment by vfremaux** [comment]
has been fixed in 3.7 and 3.6 branches, thanks
