### ISSUE TITLE
Crash when adding a checkbox

### ISSUE THREAD

**Issue by Anysia2005** [vfremaux/moodle-mod_tracker#28]
I am using 3.7 and installed the 3.7 version of the tracker and vflib. 
see the screenshoot for debugging. The plugin crashs when adding a new element like checkbox or dropdown, ...
![Bildschirmfoto 2020-04-24 um 09 50 47](https://user-images.githubusercontent.com/7451518/80188841-09319880-8612-11ea-84bf-6999a5b84d60.png)

**Comment by vfremaux** [comment]
thanks for reporting, we use the tracker in our customer service instance, and actually just upgraded it to 3.7. We check this ASAP

**Comment by vfremaux** [comment]
This was obviously a small typo error in the template name call. 37 updated for fix

**Comment by Anysia2005** [comment]
![Bildschirmfoto 2020-04-24 um 11 09 12](https://user-images.githubusercontent.com/7451518/80195402-12276780-861c-11ea-897e-f41099c29a48.png)
Unfornuately, it didn't fix it

**Comment by Anysia2005** [comment]
Error message reads File not found

**Comment by vfremaux** [comment]
i dig deeper

**Comment by Anysia2005** [comment]
Any progress on this issue??

**Comment by vfremaux** [comment]
please retreive last 3.7 version. has been fixed. Tested locally on our customer servicing moodle.
