### ISSUE TITLE
local_vflibs

### ISSUE THREAD

**Issue by alamo47ivan** [vfremaux/moodle-mod_tracker#31]
Good Morning. I don't know how to fix this error when installing the plugin. I have also tried installing the local_vflibs in the mod directory and it still gives the same error.

![Screen](https://user-images.githubusercontent.com/75943822/102017130-e7318580-3d5c-11eb-917c-2c74c00e06d2.png)

**Comment by alamo47ivan** [comment]
![Try to instal local_vflibs](https://user-images.githubusercontent.com/75943822/102017220-7343ad00-3d5d-11eb-8f41-3c0f656c7336.png)

**Comment by vfremaux** [comment]
Hi, you should avoid using the master branch which remains in an uncontrolled state. Prefer using the adequate MOODLE_XX_STABLE branches according to your local moodle version. 
vflibs is required to support some features of the tracker needing graphs, We historically support graphs using MIT JQPlot librariries and those are provided by vflibs.

Cheers.

**Comment by alamo47ivan** [comment]
Thank you very much, I had not realized that I had downloaded the master bracnh, I have already installed 3.8 and without problems. Cheers!

**Comment by ssv112** [comment]
Hi @vfremaux , I have downloaded 3.9 stable as well as  working version branches and tried to install the plugin but it still gives me same error as mentioned above ( Missing dependencies local_vflibs (2016081100)). I tried to install vfremaux/moodle-local_vflibs , 3.9 stable branch but I am getting this error after this
<img width="481" alt="Screen Shot 2021-03-16 at 10 49 31 AM" src="https://user-images.githubusercontent.com/56772933/111348955-5366a280-8646-11eb-8265-568c6e0152bd.png">
